package com.lrg.d20.combat;

public enum DamageType
{
    SLASHING, BLUDGEONING, PIERCING, RANGED, MELEE, MAGIC, GOOD_ALIGNED, EVIL_ALIGNED, LAW_ALIGNED, CHAOS_ALIGNED, NO_ALIGNMENT, 
    FIRE, ICE, DIVINE, INFERNAL, INCORPOREAL,

}

