package com.lrg.d20.character.modifier;

public enum CircumstanceType
{
    COMBAT, ADJACENT, MORALE, DODGE, COVER, BROKEN, DIVINE, UNDERWATER, DEAD, ALIVE, LIVING, FOE, ALLY, CLASS_RELATED, 
    FLANKED, POOR, RICH, GOOD, EVIL, NEUTRAL_MORALE, NEUTRAL_ETHIC, LAWFUL, CHAOTIC, RACE_RELATED, SIZE_RELATED

}
